Repository Year-3-Assignments/HMS-OSGi, pull requests merged in 2021-04, with the labels that each got.

#25 Modify code to display available doctor details in the console
  DoctorPublisher/META-INF/MANIFEST.MF
  DoctorPublisher/src/doctorpublisher/ChannelDoctor.java
  DoctorPublisher/src/doctorpublisher/DoctorService.java
  DoctorPublisher/src/doctorpublisher/DoctorServiceImpl.java
  HMS_DB/src/hms_db/DatabaseImpl.java
  PatientPublisher/src/patientpublisher/PatientPublisher.java
  PatientPublisher/src/patientpublisher/PatientPublisherImpl.java
Labels: enhancement

#23 Modify PatientPublisher bundle by adding user input to it
  DoctorPublisher/src/doctorpublisher/DoctorService.java
  DoctorPublisher/src/doctorpublisher/DoctorServiceImpl.java
  PatientManagement/.classpath
  PatientManagement/.gitignore
  PatientManagement/.project
  PatientManagement/.settings/org.eclipse.jdt.core.prefs
  PatientManagement/.settings/org.eclipse.pde.core.prefs
  PatientManagement/META-INF/MANIFEST.MF
  PatientManagement/build.properties
  PatientManagement/src/patientmanagement/Activator.java
  PatientPublisher/src/patientpublisher/PatientPublisher.java
  PatientPublisher/src/patientpublisher/PatientPublisherImpl.java
Labels: bug-fix

#24 With database connection
  ReportManagement/META-INF/MANIFEST.MF
  ReportManagement/src/reportmanagement/Activator.java
  ReportManagement/src/reportmanagement/Report.java
  ReportManagement/src/reportmanagement/ReportService.java
  ReportManagement/src/reportmanagement/ReportServiceImpl.java
Labels: enhancement

#21 Initial Pharmacy Management bundle
  PharmacyManagement/.classpath
  PharmacyManagement/.gitignore
  PharmacyManagement/.project
  PharmacyManagement/.settings/org.eclipse.jdt.core.prefs
  PharmacyManagement/.settings/org.eclipse.pde.core.prefs
  PharmacyManagement/META-INF/MANIFEST.MF
  PharmacyManagement/build.properties
  PharmacyManagement/src/pharmacyconsumer/Activator.java
  PharmacyPublisher/.classpath
  PharmacyPublisher/.gitignore
  PharmacyPublisher/.project
  PharmacyPublisher/.settings/org.eclipse.jdt.core.prefs
  PharmacyPublisher/.settings/org.eclipse.pde.core.prefs
  PharmacyPublisher/META-INF/MANIFEST.MF
  PharmacyPublisher/build.properties
  PharmacyPublisher/src/pharmacymanagement/Activator.java
  PharmacyPublisher/src/pharmacymanagement/Pharmacy.java
  PharmacyPublisher/src/pharmacymanagement/PharmacyService.java
  PharmacyPublisher/src/pharmacymanagement/PharmacyServiceImpl.java
Labels: enhancement

#29 Feature/doctor management
  DoctorManagement/.classpath
  DoctorManagement/.gitignore
  DoctorManagement/.project
  DoctorManagement/.settings/org.eclipse.jdt.core.prefs
  DoctorManagement/.settings/org.eclipse.pde.core.prefs
  DoctorManagement/META-INF/MANIFEST.MF
  DoctorManagement/build.properties
  DoctorManagement/src/doctormanagement/Activator.java
  LaboratoryPublisher/.classpath
  LaboratoryPublisher/.settings/org.eclipse.jdt.core.prefs
  ReportManagement/src/reportmanagement/ReportService.java
  ReportManagement/src/reportmanagement/ReportServiceImpl.java
Labels: enhancement

#30 Finalized hospital management system with JAR files
  DatabaseQueries/Database Queries.txt
  DirectorManagement/META-INF/MANIFEST.MF
  DirectorManagement/src/directormanagement/Activator.java
  DirectorManagement/src/directormanagement/HospitalManagement.java
  DirectorManagement/src/directormanagement/HospitalManagementImpl.java
  DoctorManagement/META-INF/MANIFEST.MF
  DoctorManagement/bin/doctormanagement/Activator.class
  DoctorManagement/src/doctormanagement/Activator.java
  DoctorPublisher/src/doctorpublisher/Activator.java
  DoctorPublisher/src/doctorpublisher/DoctorService.java
  DoctorPublisher/src/doctorpublisher/DoctorServiceImpl.java
  JAR Files/DirectorManagement.jar
  JAR Files/DoctorManagement.jar
  JAR Files/DoctorPublisher.jar
  JAR Files/HMS_DB.jar
  JAR Files/LaboratoryPublisher.jar
  JAR Files/PatientManagement.jar
  JAR Files/PatientPublisher.jar
  JAR Files/PharmacyManagement.jar
  JAR Files/PharmacyPublisher.jar
  JAR Files/ReportManagement.jar
  LaboratoryPublisher/META-INF/MANIFEST.MF
  LaboratoryPublisher/src/laboratorypublisher/LaboratoryService.java
  LaboratoryPublisher/src/laboratorypublisher/LaboratoryServiceImpl.java
  PatientManagement/src/patientmanagement/Activator.java
  PharmacyManagement/src/pharmacyconsumer/Activator.java
  PharmacyPublisher/src/pharmacymanagement/PharmacyServiceImpl.java
  ReportManagement/META-INF/MANIFEST.MF
  ReportManagement/src/reportmanagement/Activator.java
  ReportManagement/src/reportmanagement/ReportServiceImpl.java
Labels: bug-fix, enhancement
